version: '3'
services:
  web:
    image: maven:3.5-alpine
    container_name: image-search-test
    volumes:
      - .:/usr/src/mymaven
    working_dir: /usr/src/mymaven
    ports: 
      - "80:8080"
    environment:    # import env vars from terminal env vars
      - ACCESS_KEY_ID
      - ACCESS_KEY_SECRET
