# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn integration-test

  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      - DOCKER_TLS_VERIFY: "1"
      - DOCKER_HOST: "tcp://47.74.213.82:2376"
      - DOCKER_CERT_PATH: "~/.docker/machine/machines/image-search-webapp"
      - DOCKER_MACHINE_NAME: "image-search-webapp"
    steps:
      - checkout
      - run: mkdir -p $DOCKER_CERT_PATH
      - run: echo "-----BEGIN CERTIFICATE-----" > $DOCKER_CERT_PATH/ca.pem
      - run: echo $DOCKER_CA_PEM | tr " " "\n" >> $DOCKER_CERT_PATH/ca.pem
      - run: echo "-----END CERTIFICATE-----" >> $DOCKER_CERT_PATH/ca.pem
      - run: docker-compose up -d --build

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
